apiVersion: apps/v1
kind: Deployment
metadata:
  name: restauranteDB-deploy
  labels:
    app: restaurante-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurante-db
  template:
    metadata:
      labels: 
        app: restaurante-db
    spec:
    containers:
     - name: database
       image: mysql
       ports:
        - containerPort: 3306
       resources:
         requests:
           cpu: "0.5"
           memory: "700Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: restaurante-service
spec:
  selector:
    app: restaurante-db
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: restauranteapi-deploy
  labels:
    app: restauranteapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restauranteapi
  template:
    metadata:
      labels:
        app: restauranteapi
    spec:
    containers:
      - name: api
        image: mquinteiro464/restaurante
        ports:
          - containerPort: 8080
        resources:
          requests:
            cpu: "0.5"
            memory: "700Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: restauranteapi-service
spec:
  selector:
    app: restauranteapi
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      type: loadBalancer

