apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurantedbdeploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurante-db
      version: v01
  template:
    metadata:
      labels: 
        app: restaurante-db
        version: v01
    spec:
      containers:
      - name: database
        image: mysql
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: service-db
  namespace: default
spec:
  selector:
    app: restaurante-db
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  type: ClusterIP
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: restauranteapideploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restauranteapi
      version: v01
  template:
    metadata:
      labels:
        app: restauranteapi
        version: v01
    spec:
      containers:
      - name: api
        image: mquinteiro464/restaurante
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: service-api
  namespace: default
spec:
  selector:
    app: restauranteapi
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  type: LoadBalancer
