apiversion: apps/v1
kind: Deployment
metadata:
  name: restauranteDB-deploy
  labels:
    app: restaurante-db
spec:
  replicas: 1
  selector:
    matchlabels:
      app: restaurante-db
  template:
    metadata:
      labels: 
        app: restaurante-db
    spec:
    containers:
     - name: database
       image: mysql
       ports:
        - containerPort: 3306
---
apiversion: v1
kind: Service
metadata:
  name: restaurante-service
spec:
  selector:
    app: restaurante-db
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
---

apiversion: apps/v1
kind: Deployment
metadata:
  name: restauranteapi-deploy
  labels:
    app: restauranteapi
spec:
  replicas: 1
  selector:
    matchlabels:
      app: restauranteapi
  template:
    metadata:
      labels:
        app: restauranteapi
    spec:
    containers:
      - name: api
        image: mquinteiro464/restaurante
        ports:
          - containerPort: 8080
---
apiversion: v1
kind: Service
metadata:
  name: restauranteapi-service
spec:
  selector:
    app: restauranteapi
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      type: loadBalancer

