name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v2
	  
      - name: Build image
        run: docker build -t ${{ secrets.DOCKERHUB_USER }}/Restaurante

      - name: Instal doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.TOKEN }}
	
      - name: docker login
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Build and push
        uses: docker/build-push-action@v5.2.0
        with:   
          context: ./Restaurante
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/restaurante
          
      - name: definindo o context
        uses: Azure/k8s-set-context@v3.0
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG}}
       
      - name: deploy
        uses: Azure/k8s-deploy@v4.9
        with:
          images: ${{ secrets.DOCKERHUB_USER }} / restaurante:latest
          manifests: ./deployment.yaml
