name: CI-CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  CI:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: docker login
      uses: docker/login-action@v3.1.0
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
    - name: Build and push
      uses: docker/build-push-action@v5.2.0
      with:   
          context: ./Restaurante
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/restaurante
          
    - name: Doctl instal
      uses: digitalocean/action-doctl@v2.5.1
      with:   
          token: ${{secrets.TOKEN}}
          
    - name: save config cluster
      run: doctl kubernetes cluster kubeconfig save
  CD:
     runs-on: ubuntu-latest
     needs: [CI]
     steps:
       - uses: actions/checkout@v3

       - name: definindo o context
         uses: Azure/k8s-set-context@v3.0
         with:
           method: kubeconfig
           kubeconfig: ${{ secrets.KUBECONFIG}}
       - name: deploy
         uses: Azure/k8s-deploy@v4.9
         with:
           images: ${{ secrets.DOCKERHUB_USER }} / restaurante:latest
           manifests: ./deployment.yaml
